test = {   'name': 'q2_2',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(all_probs, np.ndarray)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum(all_probs) == 1.0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(all_probs) == 6\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> all_probs[3] == 0.3456\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
