test = {   'name': 'q1_2',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(num_of_names_per_year, pd.Series) \nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> pd.api.types.is_numeric_dtype(num_of_names_per_year)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> sum(num_of_names_per_year) == 175577\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(num_of_names_per_year) == 110\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
