test = {   'name': 'q2_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> 'Day' in list(calls.columns)\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> ['Wednesday', 'Friday', 'Tuesday', 'Saturday', 'Monday', 'Sunday', 'Thursday'] == list(calls['Day'].unique())\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
